### ISSUE TITLE
[Client] Milestone V1

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-client#21]
- [ ] fosscord/fosscord-web-client#20 Base Structure
- [x] fosscord/fosscord-web-client#13 Login
- [x] fosscord/fosscord-web-client#42 Register
- [ ] fosscord/fosscord-web-client#12 Friends
- [ ] fosscord/fosscord-web-client#11 User settings
- [ ] fosscord/fosscord-web-client#8 Guild settings
- [ ] fosscord/fosscord-web-client#28 Screenshare
- [x] Guilds Sidebar
- [ ] Calls/Voice channel
- [ ] Channel View
- [ ] Member Sidebar
- [ ] Plugin System
